# -*- coding: utf-8 -*-
"""Copy of Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLF634vxt-l7GEPq2FGNf7VPU0kew-h3
"""

!pip install -q \
    langchain \
    langchain-community \
    langchain-core \
    langchain-text-splitters \
    langchain-huggingface \
    langchain-pinecone \
    langchain-groq \
    pinecone \
    sentence-transformers \
    python-dotenv \
    pypdf

from langchain_community.document_loaders import PyPDFLoader, DirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from google.colab import files

uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader

def load_pdf_file(data):
    loader = PyPDFLoader(data)
    documents = loader.load()
    return documents

import os
print(os.path.exists("constitution.pdf"))

!pip install -q \
    langchain \
    langchain-community \
    langchain-core \
    langchain-text-splitters \
    langchain-huggingface \
    langchain-pinecone \
    langchain-groq \
    pinecone \
    sentence-transformers \
    python-dotenv \
    pypdf

extracted_data = load_pdf_file("constitution.pdf")

#Split the Data into Text Chunks
def text_split(extracted_data):
    text_splitter=RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=20)
    text_chunks=text_splitter.split_documents(extracted_data)
    return text_chunks

text_chunks=text_split(extracted_data)
print("Length of Text Chunks", len(text_chunks))

from langchain_huggingface import HuggingFaceEmbeddings

#Download the Embeddings from Hugging Face
def download_hugging_face_embeddings():
    embeddings=HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
    return embeddings

embeddings=download_hugging_face_embeddings()

query_result=embeddings.embed_query("This is my first project")
print("Length",len(query_result))

import os

# This one code works for BOTH Colab and Render / GitHub
try:
    # For Colab
    from google.colab import userdata
    groq_api_key = userdata.get('GROQ_API_KEY')
except:
    # For Laptop / Render / HuggingFace
    groq_api_key = os.getenv("GROQ_API_KEY")

print("Key loaded:", "Yes" if groq_api_key else "No - Add it in Secrets!")

PINECONE_API_KEY=os.environ.get('PINECONE_API_KEY')
GROQ_API_KEY=os.environ.get('GROQ_API_KEY')



from pinecone import Pinecone, ServerlessSpec

pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"])

index_name = "constition-chatbot"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )
    print("Index created successfully.")
else:
    print("Index already exists. Using existing index.")

# Load Existing index

from langchain_pinecone import PineconeVectorStore
# Embed each chunk and upsert the embeddings into your Pinecone index.
docsearch = PineconeVectorStore.from_existing_index(
    index_name=index_name,
    embedding=embeddings
)

docsearch

retriever = docsearch.as_retriever(search_type="similarity", search_kwargs={"k":3})

retrieved_docs = retriever.invoke("What is right to freedom")

retrieved_docs

from langchain_groq import ChatGroq
llm = ChatGroq(
        model="openai/gpt-oss-20b",
        temperature=0
)

# ChatPromptTemplate: Creates a structured prompt template for sending
# system instructions and user messages to the LLM.
from langchain_core.prompts import ChatPromptTemplate
# RunnablePassthrough: Passes the input data through a LangChain chain
# without changing it.
from langchain_core.runnables import RunnablePassthrough
# StrOutputParser: Converts the LLM's response into a simple string.
from langchain_core.output_parsers import StrOutputParser


system_prompt = (
    "You are an assistant for question-answering tasks. "
    "Use the following pieces of retrieved context to answer "
    "the question. If you don't know the answer, say that you "
    "don't know. Use three sentences maximum and keep the "
    "answer concise."
    "\n\n"
    "Context:\n{context}"
)

# Creates a chat prompt containing a system message and a human/user message.
prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),
])

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


rag_chain = (
    {
        "context": retriever | format_docs,
        "input": RunnablePassthrough(),
    }
    | prompt
    | llm
    | StrOutputParser()
)

response = rag_chain.invoke("If the Government imposes greater control and censorship over social media platforms to curb fake news, which fundamental rights under Article 19(1)(a), Article 19(2), and Article 21 (Right to Privacy from Puttaswamy judgment) will come into conflict, and how did the Supreme Court in Shreya Singhal v. Union of India resolve this balance?")
print(response)

response=rag_chain.invoke("explain any 1 fundamental right")
print(response)

!pip install -q langchain langchain-huggingface langchain-pinecone langchain-groq gradio pinecone

import gradio as gr
import os

# Your rag_chain must be created in SAME cell or above
# Example: make sure this part is there before chatbot function
# If you already created rag_chain in previous cell, copy that code here

def samvidhan_chatbot(question):
    if not question or not question.strip():
        return "Please ask a question"
    try:
        # rag_chain must exist
        answer = rag_chain.invoke(question)
        return answer
    except Exception as e:
        return f"Error: {e}"

demo = gr.Interface(
    fn=samvidhan_chatbot,
    inputs=gr.Textbox(label="Ask about Constitution", placeholder="What is Article 21?"),
    outputs=gr.Textbox(label="Answer", lines=8),
    title="Samvidhan AI",
    description="Indian Constitution Assistant"
)

demo.launch(
    server_name="0.0.0.0",
    server_port=int(os.environ.get("PORT" , 7860)),
    share=True  # <-- This gives you the public link
)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# import gradio as gr
# from langchain_huggingface import HuggingFaceEmbeddings
# from langchain_pinecone import PineconeVectorStore
# from langchain_groq import ChatGroq
# 
# # Read keys from HuggingFace Secrets (safe, no error)
# PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
# GROQ_API_KEY = os.getenv("GROQ_API_KEY")
# 
# print("Loading model...")
# embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
# vectorstore = PineconeVectorStore(index_name="samvidhan-index", embedding=embeddings)
# retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
# llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.2)
# 
# def chatbot(question):
#     if not question.strip():
#         return "Please ask a question"
#     docs = retriever.invoke(question)
#     context = "\n\n".join([d.page_content for d in docs])
#     prompt = f"You are Samvidhan AI. Answer from context only.\nContext: {context}\nQuestion: {question}\nAnswer:"
#     return llm.invoke(prompt).content
# 
# demo = gr.Interface(
#     fn=chatbot,
#     inputs=gr.Textbox(label="Ask about Constitution", placeholder="What is Article 21?"),
#     outputs=gr.Textbox(label="Answer", lines=8),
#     title="Samvidhan AI - Indian Constitution Assistant",
#     description="Permanent version for GitHub & HuggingFace"
# )
# 
# if __name__ == "__main__":
#     demo.launch()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# gradio
# langchain
# langchain-huggingface
# langchain-pinecone
# langchain-groq
# pinecone
# sentence-transformers
# groq

!git init
!git config --global user.email "you@example.com"
!git config --global user.name "SamvidhanAI"
!git add app.py requirements.txt
!git commit -m "Samvidhan AI - final working version"
# Create empty repo on github.com named Samvidhan-AI and copy its link
!git branch -M main
!git remote add origin https://github.com/YOUR_USERNAME/Samvidhan-AI.git
!git push -u origin main

